-- dim.period_day definition

-- Drop table

-- DROP TABLE dim.period_day;

CREATE TABLE dim.period_day (
	date_inserted_period_day timestamp DEFAULT (now())::timestamp without time zone NULL,
	inserted_by_period_day text DEFAULT 'Script'::text NULL,
	date_updated_period_day timestamp NULL,
	updated_by_period_day text NULL,
	day_dwid date NOT NULL,
	day_dd_mmm_yyyy text NULL,
	day_dd_mmm text NULL,
	day_of_week text NULL,
	day_of_week_name text NULL,
	day_of_month int4 NULL,
	day_of_quarter int4 NULL,
	day_of_year int4 NULL,
	day_weekend_flag_dwid int4 NULL,
	day_previous_dwid date NULL,
	day_previous_week_dwid date NULL,
	day_previous_month_dwid date NULL,
	day_previous_quarter_dwid date NULL,
	day_previous_year_same_day_of_week_dwid date NULL,
	day_previous_year_previous_week_same_day_of_week_dwid date NULL,
	month_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	month_mmmm_yyyy text NULL,
	month_mmmm text NULL,
	month_number int4 NULL,
	month_mmm_yyyy text NULL,
	month_mmm text NULL,
	month_yyyy_mmmm text NULL,
	month_yyyy_mmm text NULL,
	month_date_start date NULL,
	month_date_end date NULL,
	week_of_month_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	week_of_month_name text NULL,
	week_of_month_detail text NULL,
	week_of_month_number int4 NULL,
	week_of_month_number_month text NULL,
	week_of_month_month_dash_number int4 NULL,
	week_of_month_date_start date NULL,
	week_of_month_date_end date NULL,
	quarter_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	quarter_yyyyqq text NULL,
	quarter_qq_yyyy text NULL,
	quarter_qq text NULL,
	quarter_qqqq_yyyy text NULL,
	quarter_number_yyyy text NULL,
	quarter_number int4 NULL,
	quarter_date_start date NULL,
	quarter_date_end date NULL,
	week_of_quarter_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	week_of_quarter_name text NULL,
	week_of_quarter_detail text NULL,
	week_of_quarter_number int4 NULL,
	week_of_quarter_number_quarter text NULL,
	week_of_quarter_quarter_dash_number int4 NULL,
	week_of_quarter_date_start date NULL,
	week_of_quarter_date_end date NULL,
	year_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	year_yyyy text NULL,
	year_date_start date NULL,
	year_date_end date NULL,
	week_of_year_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	week_of_year_name text NULL,
	week_of_year_detail text NULL,
	week_of_year_number_year text NULL,
	week_of_year_number int4 NULL,
	week_of_year_year_dash_number int4 NULL,
	week_of_year_date_start date NULL,
	week_of_year_date_end date NULL,
	week_dwid date DEFAULT '2000-01-01'::date NOT NULL,
	week_date_start date NULL,
	week_date_end date NULL
);
